name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@51.20.8.237 << 'EOF'
            cd /home/ec2-user/caFolder/DevOps_CA  # Navigate to your project folder
            git pull origin main  # Pull the latest code from the main branch
            npm install  # Install any new dependencies
            pm2 reload all  # Reload your app via PM2
          EOF
